[WIP] Add support for noko fragments
everypolitician/scraped pull request #23
Opened 2016-11-17 18:52 UTC by chrismytton

This allows an optional `noko` parameter to `ScrapedPage` constructors, which when given will override the `noko` scope for the current instance.

```ruby
MemberRow.new(response: response, noko: noko.css('.member-row'))
```

Then in the `MemberRow` `noko` would refer to the `.member-row` element, rather than the whole page, but it would still have access to the full response.

# Related issues

I think this should close #4, because then we can just use `ScrapedPage` subclasses everywhere and just pass an extra `noko` param

# Notes to merger

This needs to have it's base changed to `master` once #21 is merged.

2016-11-17 18:59 UTC, chrismytton commented
Example of this being used to remove a custom `NokogiriDocument` class in the Mongolia scraper can be seen in https://github.com/everypolitician-scrapers/mongolia-khurai-wp-multiple-terms/pull/8.

2016-11-24 13:14 UTC, chrismytton commented
@tmtmtmtm What are your thoughts on this approach? If it seems like a reasonable approach then I'll write some documentation so we can get this PR merged.

2016-11-24 13:55 UTC, tmtmtmtm commented
Presumably this would only be on `Noko::HTML` (or conceivably `::XML`) after https://github.com/everypolitician/scraped/pull/29?

2016-11-24 14:19 UTC, chrismytton commented
> Presumably this would only be on Noko::HTML (or conceivably ::XML) after #29?

You mean `Scraped::HTML`? If so then yep, I will update this after that's merged :)

2016-11-24 16:31 UTC, chrismytton commented
@tmtmtmtm 👀

2016-11-24 17:21 UTC, tmtmtmtm requested changes
Mostly 👍 , but having the two tests, which are conceptually largely identical, be set up in slightly different ways makes it a little harder to follow what's going on that it ideally should be. 

I think it would be good to harmonise those as much as possible (e.g. either both do the `let(:page) …`, or neither does).

2016-11-24 17:52 UTC, chrismytton commented
> I think it would be good to harmonise those as much as possible (e.g. either both do the let(:page) …, or neither does).

Ooh yep, good catch! I've made the first test use `let(:page)` as well in https://github.com/everypolitician/scraped/pull/23/commits/d84d6a3734f7327c712d3527da867719cdb25aa0.

2016-11-25 08:42 UTC, tmtmtmtm reviewed
👍  — however (and sorry for not mentioning this first time around), I think we really need some docs for this too. I suspect the best example is going to be dealing with a table, where you want a MemberRow class, or equivalent, for each person.

2016-11-25 11:53 UTC, chrismytton commented
@tmtmtmtm I've added some docs in https://github.com/everypolitician/scraped/pull/23/commits/98cb4b065c83637bbc89af1633689ffc6f3d37e6. I'm not totally sure about the example I've used, it seems a bit contrived, but I think it's probably Good Enough for now.

2016-11-25 12:30 UTC, tmtmtmtm requested changes
I fear that the extra level of indirection here might make this a little too confusing as an initial example, especially as `members_term_10_table` is quite an odd field.

Perhaps drop the Table class, and go for something like this?:

```ruby
class MemberRow < Scraped::HTML
  field :name do
    noko.css('td')[2].text
  end

  field :party do
    noko.css('td')[3].text
  end
end

class AllMembersPage < Scraped::HTML
  field :members do
    noko.css('table.members-list tr').map do |row|
      MemberRow.new(response: response, noko: row)
    end
  end
end
```

2016-11-25 14:35 UTC, chrismytton commented
> I fear that the extra level of indirection here might make this a little too confusing as an initial example, especially as members_term_10_table is quite an odd field.
> 
> Perhaps drop the Table class, and go for something like this?:

👍  Yep your version is much nicer! Pushed another commit to change it to that.

2016-11-25 16:46 UTC, tmtmtmtm approved these changes
👍

2016-11-25 16:46 UTC, merged