Prototype
everypolitician/scraped pull request #7
Opened 2016-11-03 17:32 UTC by chrismytton

This uses the code from https://github.com/everypolitician-scrapers/guernsey-2016/pull/1 and https://github.com/everypolitician-scrapers/mongolia-khurai-wp-multiple-terms/pull/7 to give us a first version of the gem. Those two pull requests have also been updated to use the branch this pull request is against.

# Notes to merger

- This should not be merged until `scraped_page_archive` v0.5.0 has been released. See https://github.com/everypolitician/scraped_page_archive/pull/55.

2016-11-03 17:34 UTC, chrismytton commented
The Travis tests are failing because it needs https://github.com/everypolitician/scraped_page_archive/pull/55 to be merged and v0.5.0 of `scraped_page_archive` to be released first.

2016-11-07 12:07 UTC, chrismytton commented
@tmtmtmtm :eyes:

2016-11-07 12:30 UTC, tmtmtmtm requested changes
Mostly looking good, yay! As well as one tiny query about default logging, I think this one also falls into the territory of really wanting https://github.com/bbatsov/ruby-style-guide#one-class-per-file

2016-11-07 12:30 UTC, tmtmtmtm commented on lib/scraped_page.rb
> +        warn "[#{self.class}] #{message}"
I think I'd prefer this to be turned off by default, considering the problems that Morph has with lots of console output. Perhaps even for the first version we could have it only output warnings if an ENV var is set whilst we work out what a better approach should be?

2016-11-07 18:31 UTC, chrismytton commented on lib/scraped_page.rb
> +        warn "[#{self.class}] #{message}"
Ah yeah, this was handy while I was developing, but yep, no need for it to be on by default. I've added a `VERBOSE` environment variable to enable logging in https://github.com/everypolitician/scraped_page/pull/7/commits/6666c84ad12f863a2c142812499d92c2753b09b8.

2016-11-07 18:32 UTC, chrismytton commented
> I think this one also falls into the territory of really wanting https://github.com/bbatsov/ruby-style-guide#one-class-per-file

Yep, it was useful having it in one file when I was copying it between scrapers to test it, but no need for that now its in the gem. I've split them up in https://github.com/everypolitician/scraped_page/pull/7/commits/39f2de9f021d123361cfe89cdff2bd7ef5a02cfe.

2016-11-07 18:32 UTC, chrismytton commented
@tmtmtmtm 👀

2016-11-08 11:45 UTC, tmtmtmtm approved these changes

2016-11-08 11:45 UTC, merged